# Generated by Django 3.0.8 on 2020-10-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('creation_datetime', models.DateTimeField()),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
